In [233]:
import pyodbc
import json
import pandas as pd
from unidecode import unidecode

In [234]:
connection_string = (
    'Driver={ODBC Driver 18 for SQL Server};'
    'Server=tcp:servido-test.database.windows.net,1433;'
    'Database=test;'
    'Uid=luci_test;'
    'Pwd=Demonios24;'
    'Encrypt=yes;'
    'Connection Timeout=300;'
    'TrustServerCertificate=no;'
)

In [235]:
try:
# Establecer la conexión
    conexion = pyodbc.connect(connection_string)
    cursor = conexion.cursor()

    consulta_dataframe = "SELECT * FROM Venta"
    cursor.execute(consulta_dataframe)

    resultado = cursor.fetchall()

    nombres_columnas = [columna[0] for columna in cursor.description]

    # Convertir los datos en un diccionario
    diccionario_datos = {nombre_columna: [] for nombre_columna in nombres_columnas}
    for tupla in resultado:
        for nombre_columna, valor in zip(nombres_columnas, tupla):
            diccionario_datos[nombre_columna].append(valor)

    # Crear el DataFrame desde el diccionario
    dataframe = pd.DataFrame(diccionario_datos)
    cursor.close()
    conexion.close()
    
except pyodbc.Error as error:
    print("Ha ocurrido un error al intentar conectarse a la base de datos:", error)

In [236]:
try:
    # Establecer la conexión
    conexion = pyodbc.connect(connection_string)
    cursor = conexion.cursor()

    consulta_dataframe = "SELECT * FROM Venta"
    cursor.execute(consulta_dataframe)

    # Obtener los nombres de las columnas desde el cursor
    nombres_columnas = [columna[0] for columna in cursor.description]

    # Inicializar un diccionario para almacenar los datos
    diccionario_datos = {nombre_columna: [] for nombre_columna in nombres_columnas}

    # Iterar sobre cada fila y almacenar los valores en el diccionario
    fila = cursor.fetchone()
    while fila:
        for nombre_columna, valor in zip(nombres_columnas, fila):
            diccionario_datos[nombre_columna].append(valor)
        fila = cursor.fetchone()

    # Crear el DataFrame desde el diccionario
    dataframe = pd.DataFrame(diccionario_datos)

    cursor.close()
    conexion.close()
    
except pyodbc.Error as error:
    print("Ha ocurrido un error al intentar conectarse a la base de datos:", error)

In [237]:
dataframe

,FECHA,FACTURA,NO_PARTE,PRODUCTO,PRODUCTO_COMPLETO,MARCA,ETIQUETAS,SUBCATEGORÍA,CATEGORÍA,CAT,UNIDAD_NEGOCIO,TIPO_COMPRA,CANTIDAD,PRECIO_VENTA,COSTO_VENTA,id
0,2020-05-05,INV7778844,P373917,Alimento Lácteo Finesse,Alimento Lácteo Finesse x 6und x 150g,Finesse,Yogurt,"Lácteos, Huevos Y Refrigerados",Alimentos y Bebidas,A&B,Supermercado,Física,1,236.12,118.06,1
1,2020-02-28,INV7779415,P373917,Alimento Lácteo Finesse,Alimento Lácteo Finesse x 6und x 150g,Finesse,Yogurt,"Lácteos, Huevos Y Refrigerados",Alimentos y Bebidas,A&B,Supermercado,Física,1,236.12,118.06,2
2,2020-02-13,INV7779593,P373917,Alimento Lácteo Finesse,Alimento Lácteo Finesse x 6und x 150g,Finesse,Yogurt,"Lácteos, Huevos Y Refrigerados",Alimentos y Bebidas,A&B,Supermercado,Física,1,236.12,118.06,3
3,2020-11-02,INV7779629,P373917,Alimento Lácteo Finesse,Alimento Lácteo Finesse x 6und x 150g,Finesse,Yogurt,"Lácteos, Huevos Y Refrigerados",Alimentos y Bebidas,A&B,Supermercado,Física,1,236.12,118.06,4
4,2020-01-15,INV7779941,P373917,Alimento Lácteo Finesse,Alimento Lácteo Finesse x 6und x 150g,Finesse,Yogurt,"Lácteos, Huevos Y Refrigerados",Alimentos y Bebidas,A&B,Supermercado,Física,1,236.12,118.06,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103492,2010-04-14,INV7811191,P862774,Caldo Knorr costilla desmenchada sobre,Caldo Knorr costilla desmenchada sobre x 8 g c...,Knorr,"Condimentos, Caldos Y Sal",Despensa,Alimentos y Bebidas,A&B,Supermercado,En Línea,20,15.07,13.56,103493
103493,2010-03-30,INV7811249,P765168,Salsa San Jorge Rosada Doypack,Salsa San Jorge Rosada Doypack x 380 g,San Jorge,Salsas Y Vinagres,Despensa,Alimentos y Bebidas,A&B,Supermercado,Física,20,51.21,44.04,103494
103494,2010-03-23,INV7811302,P666583,Bolsa Ajo x55g El Rey,Bolsa Ajo x55g El Rey,El Rey,"Condimentos, Caldos Y Sal",Despensa,Alimentos y Bebidas,A&B,Supermercado,Física,20,2.46,1.92,103495
103495,2010-11-03,INV7811359,P334770,Crema de camarones Knorr,Crema de camarones Knorr x 62 g,Knorr,"Bases, Cremas Y Sopas",Despensa,Alimentos y Bebidas,A&B,Supermercado,Física,20,4.04,3.47,103496
103496,2010-02-19,INV7811464,P439859,Pasta Clásica Spaghetti Doria,Pasta Clásica Spaghetti Doria x 250 g.,Doria,Pastas,Despensa,Alimentos y Bebidas,A&B,Supermercado,Física,20,1.78,0.89,103497

In [238]:
dim_tipo_compra = dataframe[["TIPO_COMPRA"]].copy()
dim_producto= dataframe[["PRODUCTO","NO_PARTE","CATEGORÍA","MARCA","PRODUCTO_COMPLETO","SUBCATEGORÍA","UNIDAD_NEGOCIO"]].copy()

In [239]:
# Eliminar filas duplicadas y resetear el índice
dim_tipo_compra = dim_tipo_compra.drop_duplicates().reset_index(drop=True)

# Agregar un identificador único que empiece en 1
dim_tipo_compra.insert(0, 'ID_TIPO_COMPRA', range(1, len(dim_tipo_compra) + 1))

# Mostrar el DataFrame resultante
print(dim_tipo_compra)

   ID_TIPO_COMPRA TIPO_COMPRA
0               1      Física
1               2    En Línea

In [240]:
# Eliminar filas duplicadas basadas en 'NO_PARTE'
dim_producto = dim_producto.drop_duplicates(subset=['NO_PARTE'])


# Agregar una nueva columna 'ID_PRODUCTO' con un identificador único
dim_producto.insert(0, 'ID_PRODUCTO', range(1, len(dim_producto) + 1))

# Mostrar el DataFrame resultante
print(dim_producto)

        ID_PRODUCTO                                  PRODUCTO NO_PARTE  \
0                 1                   Alimento Lácteo Finesse  P373917
140               2  Yogurt Finesse Frutos Rojo x 180g Alpina  P712405
155               3                            Yogurt Finesse  P826583
156               4                Yogurt.Finesse Frutos Rojo  P881946
174               5                            Yogurt Finesse  P834875
...             ...                                       ...      ...
102809         7484            Mezcla te Suntea polvo durazno  P474155
102820         7485            Mezcla en polvo naranja Nestea  P781555
102858         7486         Mezcla Frutiño frutos rojos polvo  P279919
102879         7487           Mezcla en polvo salpicón Nestea  P623696
103342         7488             Cereal JBO frutos rojos barra  P582543

                  CATEGORÍA    MARCA  \
0       Alimentos y Bebidas  Finesse
140     Alimentos y Bebidas  Finesse
155     Alimentos y Bebidas  Finesse
156     Alimentos y Bebidas  Finesse
174     Alimentos y Bebidas  Finesse
...                     ...      ...
102809  Alimentos y Bebidas   Suntea
102820  Alimentos y Bebidas   Nestea
102858  Alimentos y Bebidas  Frutino
102879  Alimentos y Bebidas   Nestea
103342  Alimentos y Bebidas   Jbo Mp

                                   PRODUCTO_COMPLETO  \
0              Alimento Lácteo Finesse x 6und x 150g
140         Yogurt Finesse Frutos Rojo x 180g Alpina
155             Yogurt Finesse x Fresa x 180g Alpina
156         Yogurt.Finesse Frutos Rojo x 180g Alpina
174                    Yogurt Fresa Finesse X 180 gr
...                                              ...
102809                          Mezcla Polvo Durazno
102820         Mezcla en polvo naranja Nestea x 14 g
102858       Mezcla Frutiño frutos rojos polvo x 18g
102879        Mezcla en polvo salpicón Nestea x 14 g
103342  Cereal JBO frutos rojos barra x6und x23g c-u

                          SUBCATEGORÍA UNIDAD_NEGOCIO
0       Lácteos, Huevos Y Refrigerados   Supermercado
140     Lácteos, Huevos Y Refrigerados   Supermercado
155     Lácteos, Huevos Y Refrigerados   Supermercado
156     Lácteos, Huevos Y Refrigerados   Supermercado
174     Lácteos, Huevos Y Refrigerados   Supermercado
...                                ...            ...
102809                        Despensa   Supermercado
102820                        Despensa   Supermercado
102858                        Despensa   Supermercado
102879                        Despensa   Supermercado
103342                        Despensa   Supermercado

[7488 rows x 8 columns]

In [241]:
fact_venta = dataframe.copy()

In [242]:
# Unir dim_tipo_compra con fact_venta
fact_venta = pd.merge(fact_venta, dim_tipo_compra[['ID_TIPO_COMPRA', 'TIPO_COMPRA']], on='TIPO_COMPRA', how='inner')

In [243]:

fact_venta = pd.merge(fact_venta, dim_producto[['ID_PRODUCTO', 'NO_PARTE']], on='NO_PARTE', how='inner')

In [244]:

fechas = pd.date_range(start='2010-01-01', end='2030-12-31', freq='D')

# Crear DataFrame para la dimensión de tiempo
dim_tiempo = pd.DataFrame({
    'FECHA': fechas,
    'AÑO': fechas.year,
    'MES': fechas.month,
    'DIA': fechas.day,
    'DIA_SEMANA': fechas.dayofweek,
    'NOMBRE_MES': fechas.strftime('%B'),  # Nombre del mes
    'NOMBRE_DIA_SEMANA': fechas.strftime('%A')  # Nombre del día de la semana
})

# Agregar un ID único para la dimensión de tiempo
dim_tiempo['ID_TIEMPO'] = range(1, len(dim_tiempo) + 1)

dim_tiempo['NOMBRE_MES'] = dim_tiempo['NOMBRE_MES'].replace({
    'January': 'Enero', 'February': 'Febrero', 'March': 'Marzo', 'April': 'Abril',
    'May': 'Mayo', 'June': 'Junio', 'July': 'Julio', 'August': 'Agosto',
    'September': 'Septiembre', 'October': 'Octubre', 'November': 'Noviembre', 'December': 'Diciembre'
})
dim_tiempo['NOMBRE_DIA_SEMANA'] = dim_tiempo['NOMBRE_DIA_SEMANA'].replace({
    'Monday': 'Lunes', 'Tuesday': 'Martes', 'Wednesday': 'Miércoles', 'Thursday': 'Jueves',
    'Friday': 'Viernes', 'Saturday': 'Sábado', 'Sunday': 'Domingo'
})
dim_tiempo['ID_TIEMPO'] = range(1, len(dim_tiempo) + 1)

In [245]:
dim_tiempo

,FECHA,AÑO,MES,DIA,DIA_SEMANA,NOMBRE_MES,NOMBRE_DIA_SEMANA,ID_TIEMPO
0,2010-01-01,2010,1,1,4,Enero,Viernes,1
1,2010-01-02,2010,1,2,5,Enero,Sábado,2
2,2010-01-03,2010,1,3,6,Enero,Domingo,3
3,2010-01-04,2010,1,4,0,Enero,Lunes,4
4,2010-01-05,2010,1,5,1,Enero,Martes,5
...,...,...,...,...,...,...,...,...
7665,2030-12-27,2030,12,27,4,Diciembre,Viernes,7666
7666,2030-12-28,2030,12,28,5,Diciembre,Sábado,7667
7667,2030-12-29,2030,12,29,6,Diciembre,Domingo,7668
7668,2030-12-30,2030,12,30,0,Diciembre,Lunes,7669
7669,2030-12-31,2030,12,31,1,Diciembre,Martes,7670

In [246]:
# Convertir la columna 'FECHA' de fact_venta a tipo datetime
fact_venta['FECHA'] = pd.to_datetime(fact_venta['FECHA'])

In [247]:
fact_venta

,FECHA,FACTURA,NO_PARTE,PRODUCTO,PRODUCTO_COMPLETO,MARCA,ETIQUETAS,SUBCATEGORÍA,CATEGORÍA,CAT,UNIDAD_NEGOCIO,TIPO_COMPRA,CANTIDAD,PRECIO_VENTA,COSTO_VENTA,id,ID_TIPO_COMPRA,ID_PRODUCTO
0,2020-05-05,INV7778844,P373917,Alimento Lácteo Finesse,Alimento Lácteo Finesse x 6und x 150g,Finesse,Yogurt,"Lácteos, Huevos Y Refrigerados",Alimentos y Bebidas,A&B,Supermercado,Física,1,236.12,118.06,1,1,1
1,2020-02-28,INV7779415,P373917,Alimento Lácteo Finesse,Alimento Lácteo Finesse x 6und x 150g,Finesse,Yogurt,"Lácteos, Huevos Y Refrigerados",Alimentos y Bebidas,A&B,Supermercado,Física,1,236.12,118.06,2,1,1
2,2020-02-13,INV7779593,P373917,Alimento Lácteo Finesse,Alimento Lácteo Finesse x 6und x 150g,Finesse,Yogurt,"Lácteos, Huevos Y Refrigerados",Alimentos y Bebidas,A&B,Supermercado,Física,1,236.12,118.06,3,1,1
3,2020-11-02,INV7779629,P373917,Alimento Lácteo Finesse,Alimento Lácteo Finesse x 6und x 150g,Finesse,Yogurt,"Lácteos, Huevos Y Refrigerados",Alimentos y Bebidas,A&B,Supermercado,Física,1,236.12,118.06,4,1,1
4,2020-01-15,INV7779941,P373917,Alimento Lácteo Finesse,Alimento Lácteo Finesse x 6und x 150g,Finesse,Yogurt,"Lácteos, Huevos Y Refrigerados",Alimentos y Bebidas,A&B,Supermercado,Física,1,236.12,118.06,5,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103492,2010-04-14,INV7811191,P862774,Caldo Knorr costilla desmenchada sobre,Caldo Knorr costilla desmenchada sobre x 8 g c...,Knorr,"Condimentos, Caldos Y Sal",Despensa,Alimentos y Bebidas,A&B,Supermercado,En Línea,20,15.07,13.56,103493,2,1108
103493,2010-03-30,INV7811249,P765168,Salsa San Jorge Rosada Doypack,Salsa San Jorge Rosada Doypack x 380 g,San Jorge,Salsas Y Vinagres,Despensa,Alimentos y Bebidas,A&B,Supermercado,Física,20,51.21,44.04,103494,1,1379
103494,2010-03-23,INV7811302,P666583,Bolsa Ajo x55g El Rey,Bolsa Ajo x55g El Rey,El Rey,"Condimentos, Caldos Y Sal",Despensa,Alimentos y Bebidas,A&B,Supermercado,Física,20,2.46,1.92,103495,1,1140
103495,2010-11-03,INV7811359,P334770,Crema de camarones Knorr,Crema de camarones Knorr x 62 g,Knorr,"Bases, Cremas Y Sopas",Despensa,Alimentos y Bebidas,A&B,Supermercado,Física,20,4.04,3.47,103496,1,945
103496,2010-02-19,INV7811464,P439859,Pasta Clásica Spaghetti Doria,Pasta Clásica Spaghetti Doria x 250 g.,Doria,Pastas,Despensa,Alimentos y Bebidas,A&B,Supermercado,Física,20,1.78,0.89,103497,1,7373

In [248]:
# Fusionar los DataFrames usando la columna 'FECHA' como clave y mantener solo la columna 'ID_TIEMPO'
fact_venta = pd.merge(fact_venta, dim_tiempo[['FECHA', 'ID_TIEMPO']], on='FECHA', how='inner')

In [249]:
fact_venta = fact_venta[['id', 'ID_TIPO_COMPRA', 'ID_PRODUCTO','ID_TIEMPO','FACTURA','CANTIDAD','PRECIO_VENTA','COSTO_VENTA']]
# Usar el método rename para cambiar el nombre de la columna
fact_venta.rename(columns={'id': 'ID'}, inplace=True)

In [250]:

def quitar_tildes_en_dataframe(df):
    for columna in df.columns:
        # Verificar si el valor es un string antes de aplicar unidecode
        df[columna] = df[columna].apply(lambda x: unidecode(x).replace('Ñ', '<NH>').replace('ñ', '<nh>') if isinstance(x, str) else x)


# Aplicar la función a cada DataFrame
quitar_tildes_en_dataframe(fact_venta)
quitar_tildes_en_dataframe(dim_tipo_compra)
quitar_tildes_en_dataframe(dim_producto)
quitar_tildes_en_dataframe(dim_tiempo)

# Guardar los DataFrames en archivos CSV
dim_producto.to_csv('dim_producto.csv', index=False, encoding='utf-8')
dim_tipo_compra.to_csv('dim_tipo_compra.csv', index=False, encoding='utf-8')
fact_venta.to_csv('fact_venta.csv', index=False, encoding='utf-8')
dim_tiempo.to_csv('dim_tiempo.csv', index=False, encoding='utf-8')

In [251]:
dim_tipo_compra

,FECHA,AÑO,MES,DIA,DIA_SEMANA,NOMBRE_MES,NOMBRE_DIA_SEMANA,ID_TIEMPO
0,2010-01-01,2010,1,1,4,Enero,Viernes,1
1,2010-01-02,2010,1,2,5,Enero,Sabado,2
2,2010-01-03,2010,1,3,6,Enero,Domingo,3
3,2010-01-04,2010,1,4,0,Enero,Lunes,4
4,2010-01-05,2010,1,5,1,Enero,Martes,5
...,...,...,...,...,...,...,...,...
7665,2030-12-27,2030,12,27,4,Diciembre,Viernes,7666
7666,2030-12-28,2030,12,28,5,Diciembre,Sabado,7667
7667,2030-12-29,2030,12,29,6,Diciembre,Domingo,7668
7668,2030-12-30,2030,12,30,0,Diciembre,Lunes,7669
7669,2030-12-31,2030,12,31,1,Diciembre,Martes,7670